### ISSUE TITLE
Le géocatalogue est géré par le BRGM et non l'IGN

### ISSUE THREAD

**Issue by tcoupin** [UMR-PASSAGES/tutoqgis#1]
Bonjour,
Le géocatalogue est géré par le BRGM et non l'IGN :
https://github.com/UMR-PASSAGES/tutoqgis/blob/080521acb0d5285dff68ae8118d0059773f4988a/01_01_SIG.php#L138

PS : :+1: pour votre tuto

**Comment by juliepierson** [comment]
Merci pour votre retour, c'est corrigé ! Ça vous semble ok comme ça ?

**Comment by tcoupin** [comment]
Pour égaliser, je rajouterai bien un lien vers le géoportail du coup:
La métadonnée ci-dessus est tirée du catalogue de métadonnées national, le géocatalogue : www.geocatalogue.fr. Le géocatalogue est mis en oeuvre par le BRGM, la visualisation étant opérée par l'IGN au travers du géoportail (www.geoportail.gouv.fr).

**Comment by juliepierson** [comment]
Adjugé ! J'en ai fait une note du coup, vu qu'on s'éloigne un peu du sujet.
