### ISSUE TITLE
Bug dans la suppression de champs en .gpkg

### ISSUE THREAD

**Issue by cupain** [UMR-PASSAGES/tutoqgis#12]
Un bug dans QGIS apparaît au chapitre VII. 1. (Créer et supprimer des champs)
Après avoir supprimé un champ dans une couche geopackage, l'enregistrement des modifications provoque la suppression de la géométrie des entités. La suite du TP n'est donc pas pratiquable.
C'est un bug qui concerne QGIS 3.16 ([ticket créé ici](https://github.com/qgis/QGIS/issues/42768)), mais qui pourrait être signalé dans le tuto.
2 alternatives possibles :
   - utiliser une couche .shp
   - exporter la couche en .gpkg après la suppression d'un champ, mais avant de sortir du mode édition
   
---

EDIT : d'après le ticket ouvert sur le Github de QGIS, le bug concerne cette couche en particulier. La meilleure solution consisterait alors à remplacer la couche en question par une nouvelle couche .gpkg non corrompue. Exporter la couche existante dans une nouvelle couche semble résoudre le problème.

**Comment by juliepierson** [comment]
Ok, j'ai recréé la couche à partir des données admin express IGN. Chez moi c'est ok, pouvez-vous tester pour me confirmer ? Merci !

**Comment by cupain** [comment]
En effet, ça fonctionne. Merci, et bravo pour le travail réalisé !

**Comment by juliepierson** [comment]
Super, merci !
