### ISSUE TITLE
Echapper l'apostophe en SQL

### ISSUE THREAD

**Issue by cupain** [UMR-PASSAGES/tutoqgis#13]
Dans le chapitre VII. 2. (Calcul de champs), le code SQL suivant est proposé pour attribuer le nom de département à chaque entité : 
```
CASE
WHEN "INSEE_DEP" = '29' THEN 'Finistère'
WHEN "INSEE_DEP" = '22' THEN 'Côtes-d\'Armor'
WHEN "INSEE_DEP" = '35' THEN 'Ille-et-Vilaine'
WHEN "INSEE_DEP" = '56' THEN 'Morbihan'
END
```

L’algorithme fonctionne ainsi, mais l'interpréteur graphique avant l’exécution ne reconnaît pas l'échappement de l'apostrophe par la méthode " \\' " ; le code couleur ne s'applique donc pas correctement.

Il serait plus propre d'utiliser la double apostrophe : 

```
CASE
WHEN "INSEE_DEP" = '29' THEN 'Finistère'
WHEN "INSEE_DEP" = '22' THEN 'Côtes-d''Armor'
WHEN "INSEE_DEP" = '35' THEN 'Ille-et-Vilaine'
WHEN "INSEE_DEP" = '56' THEN 'Morbihan'
END
```

**Comment by juliepierson** [comment]
Bien vu, merci ! C'est corrigé.
